from data.exceptions.base import AuthError


class EmailNotAvailableError(AuthError): ...
